export const topics = [
  {
    id: 'data-structures',
    label: 'Data Structures',
    children: [
      { id: 'big-o', label: 'Complexity Analysis (Order of Growth, Big-O / Theta / Omega, Time & Space)', category: 'Foundation', blurb: 'State time and space complexity for every operation you mention, and explain amortized cost (e.g., why appending to a dynamic array is O(1) on average).' },
      { id: 'recursion', label: 'Recursion (incl. Analysis of Recursion)', category: 'Foundation' },
      { id: 'arrays', label: 'Arrays & Dynamic Arrays', category: 'Linear Structures', blurb: 'Indexing, insertion/deletion costs, resizing, and patterns like two pointers, sliding window, and prefix sums.' },
      { id: 'strings', label: 'Strings', category: 'Linear Structures', blurb: 'Immutability, building strings efficiently, and common problems like anagrams, palindromes, and substring search.' },
      { id: 'matrix', label: 'Matrix (2D Arrays)', category: 'Linear Structures' },
      { id: 'hash-tables', label: 'Hashing (Hash Tables, Chaining, Open Addressing)', category: 'Linear Structures', blurb: "How hashing works, collisions (chaining vs. open addressing), load factor, and why lookups are O(1) average but O(n) worst case. The most-used tool in interview solutions." },
      { id: 'linked-lists', label: 'Linked Lists (Singly, Doubly, Circular)', category: 'Linear Structures', blurb: 'Singly vs. doubly linked, reversal, cycle detection (fast/slow pointers), merging, and when they beat arrays.' },
      { id: 'stacks', label: 'Stacks', category: 'Linear Structures' },
      { id: 'queues', label: 'Queues', category: 'Linear Structures' },
      { id: 'deques', label: 'Deques', category: 'Linear Structures' },
      { id: 'binary-trees', label: 'Binary Trees (Traversals)', category: 'Trees & Graphs', blurb: 'Traversals (pre/in/post-order, level-order), recursion vs. iteration, height, and path problems.' },
      { id: 'bst', label: 'Binary Search Trees', category: 'Trees & Graphs', blurb: 'The ordering property, search/insert/delete, validating a BST, and why balance matters (brief awareness of AVL/red-black trees is enough).' },
      { id: 'heaps', label: 'Heaps / Priority Queues', category: 'Trees & Graphs', blurb: 'Min-heap vs. max-heap, heapify, and classic uses like top-k elements and merging sorted lists.' },
      { id: 'graphs', label: 'Graphs (Representation)', category: 'Trees & Graphs', blurb: 'Adjacency list vs. matrix, BFS vs. DFS, cycle detection, topological sort, and shortest paths (Dijkstra at a conceptual level).' },
      { id: 'tries', label: 'Tries', category: 'Good to Know', blurb: 'Prefix trees for autocomplete and word-search problems.' },
      { id: 'union-find', label: 'Union-Find (Disjoint Set)', category: 'Good to Know', blurb: 'Connected components, with path compression and union by rank.' },
      { id: 'balanced-trees', label: 'Balanced Trees (AVL, Red-Black)', category: 'Good to Know' },
      { id: 'segment-fenwick-tree', label: 'Segment Tree & Fenwick Tree', category: 'Good to Know' },
    ],
  },
  {
    id: 'algorithms',
    label: 'Algorithms',
    children: [
      { id: 'searching', label: 'Searching (Linear, Binary)', category: 'Search & Sort' },
      { id: 'sorting', label: 'Sorting (Comparison & Non-Comparison, Stability)', category: 'Search & Sort' },
      { id: 'divide-conquer', label: 'Divide & Conquer', category: 'Paradigms' },
      { id: 'greedy', label: 'Greedy', category: 'Paradigms' },
      { id: 'backtracking', label: 'Backtracking', category: 'Paradigms' },
      { id: 'dynamic-programming', label: 'Dynamic Programming', category: 'Paradigms' },
      { id: 'bfs-dfs', label: 'BFS & DFS', category: 'Graph Algorithms' },
      { id: 'topological-sort', label: 'Topological Sort', category: 'Graph Algorithms' },
      { id: 'shortest-paths', label: 'Shortest Paths (Dijkstra, Bellman-Ford, Floyd-Warshall)', category: 'Graph Algorithms' },
      { id: 'mst', label: 'Minimum Spanning Tree (Prim, Kruskal)', category: 'Graph Algorithms' },
      { id: 'bit-manipulation', label: 'Bit Manipulation', category: 'Good to Know' },
      { id: 'number-theory', label: 'Number Theory Basics (Sieve, Modular Exponentiation)', category: 'Good to Know' },
      { id: 'string-matching', label: 'String Matching (KMP, Rabin-Karp)', category: 'Good to Know' },
    ],
  },
  {
    id: 'patterns',
    label: 'Patterns',
    children: [
      { id: 'two-pointers', label: 'Two Pointers', category: 'Arrays & Strings' },
      { id: 'sliding-window', label: 'Sliding Window (Fixed, Variable)', category: 'Arrays & Strings' },
      { id: 'prefix-sum-diff', label: 'Prefix Sum & Difference Array', category: 'Arrays & Strings' },
      { id: 'intervals', label: 'Intervals', category: 'Arrays & Strings' },
      { id: 'fast-slow-pointers', label: 'Fast / Slow Pointers', category: 'Pointers & Stacks' },
      { id: 'monotonic-stack-deque', label: 'Monotonic Stack & Deque', category: 'Pointers & Stacks' },
      { id: 'binary-search-on-answer', label: 'Binary Search on Answer', category: 'Search & Heaps' },
      { id: 'topk-two-heaps', label: 'Top-K / Two Heaps', category: 'Search & Heaps' },
      { id: 'bfs-dfs-grids', label: 'BFS / DFS on Grids (incl. Multi-Source BFS)', category: 'Search & Heaps' },
      { id: 'dp-1d-grid', label: '1D & Grid DP', category: 'DP Patterns' },
      { id: 'dp-subsequence-knapsack', label: 'Subsequence & Knapsack', category: 'DP Patterns' },
      { id: 'dp-string', label: 'String DP (LCS, Edit Distance)', category: 'DP Patterns' },
      { id: 'lis', label: 'LIS', category: 'DP Patterns' },
      { id: 'dp-partition', label: 'Partition DP', category: 'DP Patterns' },
    ],
  },
]
