export const topics = [
  {
    id: 'data-structures',
    label: 'Data Structures',
    children: [
      { id: 'big-o', label: 'Big-O Complexity (time, space, amortized)', category: 'Foundation', blurb: 'State time and space complexity for every operation you mention, and explain amortized cost (e.g., why appending to a dynamic array is O(1) on average).' },
      { id: 'arrays', label: 'Arrays & Dynamic Arrays', category: 'Foundation', blurb: 'Indexing, insertion/deletion costs, resizing, and patterns like two pointers, sliding window, and prefix sums.' },
      { id: 'strings', label: 'Strings', category: 'Foundation', blurb: 'Immutability, building strings efficiently, and common problems like anagrams, palindromes, and substring search.' },
      { id: 'hash-tables', label: 'Hash Tables (Maps & Sets)', category: 'Foundation', blurb: "How hashing works, collisions (chaining vs. open addressing), load factor, and why lookups are O(1) average but O(n) worst case. The most-used tool in interview solutions." },
      { id: 'linked-lists', label: 'Linked Lists', category: 'Core Linear Structures', blurb: 'Singly vs. doubly linked, reversal, cycle detection (fast/slow pointers), merging, and when they beat arrays.' },
      { id: 'stacks-queues', label: 'Stacks & Queues', category: 'Core Linear Structures', blurb: 'LIFO vs. FIFO, implementing one with the other, monotonic stacks, and deques.' },
      { id: 'recursion', label: 'Recursion', category: 'Core Linear Structures' },
      { id: 'binary-trees', label: 'Binary Trees', category: 'Trees & Graphs', blurb: 'Traversals (pre/in/post-order, level-order), recursion vs. iteration, height, and path problems.' },
      { id: 'bst', label: 'Binary Search Trees (incl. AVL, B-trees)', category: 'Trees & Graphs', blurb: 'The ordering property, search/insert/delete, validating a BST, and why balance matters (brief awareness of AVL/red-black trees is enough).' },
      { id: 'heaps', label: 'Heaps / Priority Queues', category: 'Trees & Graphs', blurb: 'Min-heap vs. max-heap, heapify, and classic uses like top-k elements and merging sorted lists.' },
      { id: 'graphs', label: 'Graphs', category: 'Trees & Graphs', blurb: 'Adjacency list vs. matrix, BFS vs. DFS, cycle detection, topological sort, and shortest paths (Dijkstra at a conceptual level).' },
      { id: 'tries', label: 'Tries', category: 'Good to Know', blurb: 'Prefix trees for autocomplete and word-search problems.' },
      { id: 'union-find', label: 'Union-Find (Disjoint Set)', category: 'Good to Know', blurb: 'Connected components, with path compression and union by rank.' },
    ],
  },
  {
    id: 'algorithms',
    label: 'Algorithms',
    children: [
      { id: 'binary-search', label: 'Binary Search', category: 'Search & Sort' },
      { id: 'sorting', label: 'Sorting', category: 'Search & Sort' },
      { id: 'divide-conquer', label: 'Divide & Conquer', category: 'Search & Sort' },
      { id: 'greedy', label: 'Greedy', category: 'Paradigms' },
      { id: 'backtracking', label: 'Backtracking', category: 'Paradigms' },
      { id: 'dynamic-programming', label: 'Dynamic Programming', category: 'Paradigms' },
      { id: 'bfs-dfs', label: 'BFS & DFS', category: 'Graph Algorithms' },
      { id: 'topological-sort', label: 'Topological Sort', category: 'Graph Algorithms' },
      { id: 'shortest-paths', label: 'Shortest Paths (Dijkstra)', category: 'Graph Algorithms' },
    ],
  },
  {
    id: 'patterns',
    label: 'Patterns',
    children: [
      { id: 'two-pointers', label: 'Two Pointers', category: 'Arrays & Strings' },
      { id: 'sliding-window', label: 'Sliding Window', category: 'Arrays & Strings' },
      { id: 'prefix-sums', label: 'Prefix Sums', category: 'Arrays & Strings' },
      { id: 'intervals', label: 'Intervals', category: 'Arrays & Strings' },
      { id: 'fast-slow-pointers', label: 'Fast / Slow Pointers', category: 'Pointers & Stacks' },
      { id: 'monotonic-stack', label: 'Monotonic Stack', category: 'Pointers & Stacks' },
      { id: 'bfs-dfs-grids', label: 'BFS / DFS on Grids & Graphs', category: 'Search & Heaps' },
      { id: 'two-heaps-topk', label: 'Two Heaps / Top-K', category: 'Search & Heaps' },
      { id: 'dp-1d-2d-knapsack', label: '1D, 2D, Knapsack', category: 'DP Patterns' },
    ],
  },
  {
    id: 'cs-fundamentals',
    label: 'CS Fundamentals',
    children: [
      { id: 'processes-vs-threads', label: 'Processes vs Threads', category: 'Operating Systems' },
      { id: 'scheduling', label: 'Scheduling', category: 'Operating Systems' },
      { id: 'memory-virtual-memory', label: 'Memory & Virtual Memory', category: 'Operating Systems' },
      { id: 'deadlocks', label: 'Deadlocks', category: 'Operating Systems' },
      { id: 'race-conditions', label: 'Race Conditions', category: 'Concurrency' },
      { id: 'locks-semaphores', label: 'Locks & Semaphores', category: 'Concurrency' },
      { id: 'synchronization', label: 'Synchronization', category: 'Concurrency' },
      { id: 'sql-joins', label: 'SQL & Joins', category: 'Databases' },
      { id: 'indexing', label: 'Indexing', category: 'Databases' },
      { id: 'normalization', label: 'Normalization', category: 'Databases' },
      { id: 'transactions-acid', label: 'Transactions (ACID)', category: 'Databases' },
      { id: 'sql-vs-nosql', label: 'SQL vs NoSQL', category: 'Databases' },
      { id: 'tcp-vs-udp', label: 'TCP vs UDP', category: 'Networking' },
      { id: 'http-https', label: 'HTTP / HTTPS', category: 'Networking' },
      { id: 'dns', label: 'DNS', category: 'Networking' },
      { id: 'rest-basics', label: 'REST Basics', category: 'Networking' },
    ],
  },
  {
    id: 'design-behavioral',
    label: 'Design & Behavioral',
    children: [
      { id: 'oop-pillars', label: 'OOP Pillars', category: 'OOP & Design' },
      { id: 'solid', label: 'SOLID', category: 'OOP & Design' },
      { id: 'design-patterns', label: 'Design Patterns (Singleton, Factory, Observer, Strategy)', category: 'OOP & Design' },
      { id: 'caching', label: 'Caching', category: 'System Design Basics' },
      { id: 'load-balancing', label: 'Load Balancing', category: 'System Design Basics' },
      { id: 'sharding-replication', label: 'Sharding & Replication', category: 'System Design Basics' },
      { id: 'cap-theorem', label: 'CAP Theorem', category: 'System Design Basics' },
      { id: 'api-design', label: 'API Design', category: 'System Design Basics' },
      { id: 'star-stories', label: 'STAR Stories', category: 'Behavioral' },
    ],
  },
]
